services:
  userauthsystem:
    image: ${DOCKER_REGISTRY-}userauthsystem
    build:
      context: .
      dockerfile: UserAuthSystem/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
        - UserAuthSystemDB
    networks:
      - UserAuthSystem-network
  
  UserAuthSystemDB:
    image: postgres:15
    container_name: UserAuthSystemDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: UserAuthSystem
    ports:
      - 5432:5432
    networks:
      - UserAuthSystem-network
volumes:
 postgres_data: 

networks:
 UserAuthSystem-network:
    driver: bridge
